# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-22 05:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('filetype', models.IntegerField(default=2)),
            ],
        ),
    ]
