# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-17 07:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spark', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='fraudphone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phonenumber', models.CharField(max_length=50)),
                ('phonecontent', models.TextField()),
                ('phonefilename', models.CharField(max_length=100)),
                ('phonetype', models.IntegerField(default=2)),
            ],
        ),
    ]
